// Copyright 2026 Ryan P. Walsh (rpwalsh.github.io)
import type { Activity } from '@code-retrainer/activities';
import { activityFileSchema } from '@code-retrainer/activities';
import type { JsonValue } from '@code-retrainer/core';
import { z } from 'zod';

/**
 * The activity content, fetched rather than bundled into the script.
 *
 * A hundred kilobytes of questions has no business being parsed before the
 * first paint, and it changes on a completely different schedule from the
 * code. Fetched once, on demand, when someone opens the practice screen.
 */
export interface CurriculumActivities {
  readonly id: string;
  readonly title: string;
  readonly summary: string;
  readonly skills: readonly {
    readonly id: string;
    readonly name: string;
    readonly category: string;
  }[];
  readonly activities: readonly Activity[];
}

const documentSchema = z.object({
  curricula: z.array(
    z
      .object({
        id: z.string().min(1),
        title: z.string().min(1),
        summary: z.string().min(1),
        skills: z.array(z.object({ id: z.string(), name: z.string(), category: z.string() })),
      })
      .extend({ activities: activityFileSchema.shape.activities }),
  ),
});

export async function fetchActivities(): Promise<readonly CurriculumActivities[]> {
  const response = await fetch('content/activities.json');
  if (!response.ok) {
    throw new Error(`Could not load activities (${response.status})`);
  }

  // Validated on arrival rather than trusted: this file is generated by a
  // separate command, and a stale or half-written one should say so here
  // rather than crash inside a component three screens later.
  const parsed = documentSchema.parse((await response.json()) as JsonValue);
  return parsed.curricula;
}

/**
 * Draw a run from one curriculum.
 *
 * Weakest first when there is history, otherwise easiest first, and always in
 * a stable order for a given seed so that reloading the page does not reshuffle
 * a session someone is halfway through.
 */
export function drawRun(
  set: CurriculumActivities,
  size: number,
  seen: ReadonlySet<string>,
): readonly Activity[] {
  const unseen = set.activities.filter((activity) => !seen.has(activity.id));
  // Everything already answered goes back in the pool once the new material
  // runs out, rather than the screen saying "nothing left to do".
  const pool =
    unseen.length >= size ? unseen : [...unseen, ...set.activities.filter((a) => seen.has(a.id))];

  return [...pool]
    .sort((a, b) => a.difficulty - b.difficulty || a.id.localeCompare(b.id))
    .slice(0, size);
}
